### PR TITLE
Issue 88

### PR DESCRIPTION
**Pull request by Nivedita79**

### CODE REVIEW

**Comment by wdduncan** [comment]
I am not able to open the dental_material_import.owl file for review.

image

**Comment by Nivedita79** [comment]
Yes Bill, from yesterday I am facing the same problem, Unable to open the
file.
---------------------------
*Dr. Nivedita Dutta (Chowdhury).*
*B.D.S, PhD*
*Recipient of Women Scientist fellowship, DST, Govt. of India *
*Dental Surgeon, Clinical Researcher*
*Durgapur -713213*

*Orcid ID: https://orcid.org/0000-0001-6424-4096
<https://orcid.org/0000-0001-6424-4096>*

**Comment by wdduncan** [comment]
Please address the following:
- [ ] Names/labels are lower case unless you are using a proper name
- [ ] Glass ionomer cement need definition
- [ ] Conventional Glass Ionomer Cement needs definition
- [ ] High Viscosity Glass Ionomer Cement needs definition
- [ ] 'Zinc Oxide Eugenol Cement' needs definition
- [ ] 'Zinc Oxide Non-Eugenol Cement' needs definition
- [ ] 'Hybrid all purpose' needs definition
- Macrofilled needs definition
- [ ] 'Small Particle' needs definition
- [ ]  definitions need to be in genus-differentia form (A is a B that C). For example see definition of 'metal dental restoration material'.

**Comment by wdduncan** [comment]
Following up on todays meeting: 
The classes `glass ionomer` and `zinc oxide` should be top level classes. We will add alternative terms `glass ionomer cement` and `GIC` to `glass ionomer`.

**Comment by wdduncan** [comment]
The main `ohd-edit` files seems to be broken in this PR. We need to make sure we fix it before merging.

**Comment by Nivedita79** [comment]
> 

The term “glass-ionomer” was applied to them in the earliest publication [[2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5040989/#B2-jfb-07-00016)], but is not strictly correct. The proper name for them, according to the International Organization for Standardization, ISO, is “glass polyalkenoate cement” [[3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5040989/#B3-jfb-07-00016)], but the term “glass-ionomer” (including the hyphen) is recognised as an acceptable trivial name [[4](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5040989/#B4-jfb-07-00016)], and is widely used within the dental profession.

**Review by wdduncan — APPROVED** [review]

**Review by wdduncan — APPROVED** [review]

**Comment by wdduncan** [comment]
@Nivedita79 I replace definitions beginning with "A cement dental restoration ..." with "A dental restoration ..." (i.e., I removed 'cement').   
I do not see a resolution in the near future for defining precisely what it means for a material to be a cement. I would like to finish this PR so that I can merge it. We can return to the discussion about to define what a cement is.

**Comment by Nivedita79** [comment]
Okay.

---------------------------
*Dr. Nivedita Dutta (Chowdhury).*
*B.D.S, PhD*
*Recipient of Women Scientist fellowship, DST, Govt. of India *
*Dental Surgeon, Clinical Researcher*
*Durgapur -713213*

*Orcid ID: https://orcid.org/0000-0001-6424-4096
<https://orcid.org/0000-0001-6424-4096>*

**Pull request merged**
